# Generated by Django 4.0.4 on 2022-06-08 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 8, 7, 23, 33, 779849, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='myuser',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
