# Generated by Django 4.0.4 on 2022-06-08 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_myuser_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 8, 7, 24, 18, 529740, tzinfo=utc)),
        ),
    ]
